import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { useRouter } from 'next/navigation';
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const router = useRouter();
const pathname = usePathname();

useEffect(() => {
  const accessToken = localStorage.getItem('accessToken');
  if (!accessToken && pathname !== '/login') {
    router.push('/login');
  }
  if (!accessToken && pathname !== '/login') {
    router.push('/dashboard');
  }
}, [pathname, router]);

export const meta: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}